/* Customer feedback — a separate, controlled channel from internal Kudos.

   A customer never signs in. The only "authentication" is possession of a
   single-use, expiring, opaque token generated by Admin/HR for a specific
   technician (optionally a specific store) — a demo-safe stand-in for a real
   QR/link tied to a completed service visit, not a real customer-identity
   check. That gap is called out explicitly wherever the token surfaces.

   This never changes anyone's pay by itself: `linkedToIncentive` on a
   feedback record only ever gets set by a distinct, explicit action (not
   built in this pass), and nothing in the incentive engine reads customer
   feedback at all — moderating a piece of feedback decides its visibility,
   nothing else. */

const FEEDBACK_RATING_LABEL = { 1: 'Poor', 2: 'Fair', 3: 'Good', 4: 'Very good', 5: 'Excellent' };

/* ---- Customer-facing submission — no login, reached via ?feedback=TOKEN ---- */
function CustomerFeedbackForm({ token }) {
  const store = useStore();
  const [rating, setRating] = useState(0);
  const [badge, setBadge] = useState('');
  const [comment, setComment] = useState('');
  const [customerName, setCustomerName] = useState('');
  const [customerPhone, setCustomerPhone] = useState('');
  const [consent, setConsent] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [err, setErr] = useState('');

  const tok = store.getFeedbackToken(token);
  const emp = tok ? store.getEmployee(tok.empId) : null;
  const site = tok && tok.siteId ? store.getSite(tok.siteId) : null;
  const expired = tok && new Date(tok.expiresAt) < new Date();
  const invalid = !tok || tok.used || expired;

  const submit = () => {
    if (!rating) { setErr('Please choose a rating.'); return; }
    if (!consent) { setErr('Please confirm you agree to share this feedback.'); return; }
    const res = Store.submitFeedback(token, { rating, badge, comment, customerName, customerPhone });
    if (res && res.error) { setErr(res.error); return; }
    setSubmitted(true);
  };

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-[#0B0F1A] flex items-center justify-center p-4">
      <div className="w-full max-w-md bg-white dark:bg-slate-900 rounded-2xl shadow-pop border border-slate-200 dark:border-slate-800 overflow-hidden">
        <div className="p-5 border-b border-slate-100 dark:border-slate-800 flex items-center gap-3">
          <BrandLogo size={32}/>
          <div>
            <div className="text-[13px] font-bold text-slate-900 dark:text-white">Rate your service visit</div>
            <div className="text-[10.5px] text-slate-500">S.D. Computronix — customer feedback</div>
          </div>
        </div>

        <div className="p-5 space-y-4">
          {invalid ? (
            <Empty icon="alert" title={!tok ? 'This link is not valid' : tok.used ? 'This link has already been used' : 'This link has expired'}
              hint="Feedback links are single-use and expire after a couple of weeks. Ask the technician or store for a fresh link if you'd still like to share feedback."/>
          ) : submitted ? (
            <div className="text-center py-4 space-y-2">
              <div className="w-14 h-14 rounded-full bg-emerald-50 dark:bg-emerald-900/30 text-emerald-600 flex items-center justify-center mx-auto">
                <Icon name="check-circle" className="w-7 h-7"/>
              </div>
              <div className="text-[14px] font-bold text-slate-900 dark:text-white">Thank you!</div>
              <div className="text-[12px] text-slate-500">Your feedback has been sent for review. It helps {emp.name.split(' ')[0]} and the team.</div>
            </div>
          ) : (
            <>
              <div className="flex items-center gap-3 p-3 rounded-xl bg-slate-50 dark:bg-slate-800/60">
                <Avatar emp={emp} size={40}/>
                <div className="min-w-0">
                  <div className="text-[13px] font-bold text-slate-900 dark:text-white truncate">{emp.name}</div>
                  <div className="text-[10.5px] text-slate-500 truncate">{emp.code}{site ? ` · ${site.name} (${site.code})` : ''}</div>
                </div>
              </div>

              <div>
                <div className="text-[11px] font-bold uppercase tracking-wide text-slate-500 mb-1.5">How was your experience?</div>
                <div className="flex items-center gap-1.5">
                  {[1, 2, 3, 4, 5].map((n) => (
                    <button key={n} type="button" onClick={() => setRating(n)} aria-label={`${n} star${n === 1 ? '' : 's'}`}
                      className="w-10 h-10 flex items-center justify-center">
                      <Icon name="award" className={`w-7 h-7 transition ${n <= rating ? 'text-amber-500' : 'text-slate-200 dark:text-slate-700'}`}/>
                    </button>
                  ))}
                </div>
                {rating > 0 && <div className="text-[11px] text-slate-500 mt-0.5">{FEEDBACK_RATING_LABEL[rating]}</div>}
              </div>

              <Field label="What stood out? (optional)">
                <Select value={badge} onChange={(e) => setBadge(e.target.value)}>
                  <option value="">— Select a reason —</option>
                  {KUDOS_BADGES.map((b) => <option key={b} value={b}>{b}</option>)}
                </Select>
              </Field>

              <Field label="Tell us more (optional)">
                <Textarea value={comment} onChange={(e) => setComment(e.target.value)} placeholder="What went well, or what could be better?"/>
              </Field>

              <div className="grid grid-cols-2 gap-2.5">
                <Field label="Your name (optional)"><Input value={customerName} onChange={(e) => setCustomerName(e.target.value)} placeholder="Optional"/></Field>
                <Field label="Your phone (optional)"><Input value={customerPhone} onChange={(e) => setCustomerPhone(e.target.value)} placeholder="Optional"/></Field>
              </div>
              <div className="text-[10px] text-slate-400">Only used to follow up if needed — never shown to the technician, and masked internally.</div>

              <label className="flex items-start gap-2 text-[11px] text-slate-600 dark:text-slate-300 cursor-pointer">
                <input type="checkbox" checked={consent} onChange={(e) => setConsent(e.target.checked)} className="accent-brand-700 w-4 h-4 mt-0.5 shrink-0"/>
                I agree this feedback may be shared internally with S.D. Computronix for service quality review.
              </label>

              {err && <div className="text-[11.5px] text-rose-600 font-semibold">{err}</div>}

              <button onClick={submit} className="w-full h-11 rounded-xl bg-brand-700 hover:bg-brand-800 text-white text-[13px] font-bold">
                Submit feedback
              </button>
            </>
          )}
        </div>
        <div className="px-5 pb-4 text-[9.5px] text-slate-400 text-center">
          Demo mode — this link is not authenticated against a real customer identity.
        </div>
      </div>
    </div>
  );
}

/* ---- Internal: moderation queue + token generator (Admin/HR) ---- */
function FeedbackTokenGenerator({ user }) {
  const store = useStore();
  const toast = useToast();
  const [empId, setEmpId] = useState('');
  const [generated, setGenerated] = useState(null);
  const emp = empId ? store.getEmployee(empId) : null;

  const generate = () => {
    if (!emp) { toast('Pick a technician first', 'warn'); return; }
    const res = Store.generateFeedbackToken(emp.id, emp.siteId, user);
    if (res && res.error) { toast(res.error, 'error'); return; }
    setGenerated(res);
  };
  const link = generated ? `${(typeof location !== 'undefined' && location.origin + location.pathname) || ''}?feedback=${generated.token}` : '';

  return (
    <Card title="Generate a feedback link" subtitle="Demo-safe, single-use link for a completed visit — not a real customer-identity check" bodyClass="p-3">
      <div className="space-y-2.5">
        <Field label="Technician"><EmployeePicker value={empId} onChange={(v) => { setEmpId(v); setGenerated(null); }}/></Field>
        <Btn variant="primary" disabled={!emp} onClick={generate}><Icon name="send" className="w-3.5 h-3.5"/>Generate link</Btn>
        {generated && (
          <div className="p-2.5 rounded-lg bg-emerald-50 dark:bg-emerald-900/20 border border-emerald-200 dark:border-emerald-800 space-y-1.5">
            <div className="text-[11px] text-emerald-800 dark:text-emerald-200 font-semibold">Link ready — expires {fmtDate(generated.expiresAt, { year: true })}, single use</div>
            <div className="text-[11px] font-mono text-slate-700 dark:text-slate-200 break-all bg-white dark:bg-slate-900 p-2 rounded border border-emerald-200 dark:border-emerald-800">{link}</div>
          </div>
        )}
      </div>
    </Card>
  );
}

function CustomerFeedbackPage({ user }) {
  const store = useStore();
  const toast = useToast();
  const [status, setStatus] = useState('pending');
  const canModerate = can(user, 'feedback.moderate');
  const canGenerate = can(user, 'feedback.generate');

  const list = store.getFeedback(status === 'all' ? null : { status });
  const counts = {
    pending: store.getFeedback({ status: 'pending' }).length,
    approved: store.getFeedback({ status: 'approved' }).length,
    rejected: store.getFeedback({ status: 'rejected' }).length,
    flagged: store.getFeedback({ status: 'flagged' }).length,
  };

  const decide = (f, decision) => {
    const res = Store.moderateFeedback(f.id, decision, user);
    if (res && res.error) { toast(res.error, 'error'); return; }
    toast(`Marked ${decision}`, decision === 'approved' ? 'success' : 'warn');
  };

  const TABS = [
    { id: 'pending', label: 'Pending', count: counts.pending },
    { id: 'approved', label: 'Approved', count: counts.approved },
    { id: 'flagged', label: 'Flagged', count: counts.flagged },
    { id: 'rejected', label: 'Rejected', count: counts.rejected },
    { id: 'all', label: 'All', count: list.length },
  ];

  return (
    <div className="space-y-4">
      <PageHeader eyebrow="People" title="Customer Feedback"
        subtitle="A separate, moderated channel from internal Kudos — feedback never changes pay by itself.">
        <Badge tone="amber">{counts.pending} pending review</Badge>
      </PageHeader>

      {canGenerate && <FeedbackTokenGenerator user={user}/>}

      <div className="flex items-center gap-1.5 flex-wrap">
        {TABS.map((t) => (
          <button key={t.id} type="button" onClick={() => setStatus(t.id)}
            className={`h-8 px-3 rounded-full text-[12px] font-semibold border transition ${
              status === t.id ? 'bg-brand-700 border-brand-700 text-white' : 'border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-300'}`}>
            {t.label} <span className={status === t.id ? 'opacity-80' : 'text-slate-400'}>· {t.count}</span>
          </button>
        ))}
      </div>

      <Card noBody bodyClass="p-0">
        {list.length === 0 ? (
          <Empty icon="sparkle" title="No feedback here" hint="Feedback submitted through a generated link will show up here for review."/>
        ) : (
          <div className="divide-y divide-slate-100 dark:divide-slate-800">
            {list.map((f) => {
              const emp = store.getEmployee(f.empId);
              const site = f.siteId ? store.getSite(f.siteId) : null;
              return (
                <div key={f.id} className="p-3 flex items-start gap-3">
                  {emp && <EmployeeIdentity emp={emp} size="md"/>}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 flex-wrap">
                      {site && <StoreIdentity site={site}/>}
                      <span className="text-[11px] font-bold text-amber-600">{'★'.repeat(f.rating)}{'☆'.repeat(5 - f.rating)}</span>
                      {f.badge && <Badge tone="violet">{f.badge}</Badge>}
                      <StatusBadge status={f.status}/>
                    </div>
                    {f.comment && <div className="text-[12px] text-slate-700 dark:text-slate-200 mt-1">"{f.comment}"</div>}
                    <div className="text-[10.5px] text-slate-400 mt-1">
                      {f.customer.nameMasked || 'Anonymous'}{f.customer.phoneMasked ? ` · ${f.customer.phoneMasked}` : ''} · {fmtDateTime(f.submittedAt)}
                      {f.moderatedBy && <> · {f.status} by {f.moderatedBy} on {fmtDate(f.moderatedAt, { year: true })}</>}
                    </div>
                  </div>
                  {canModerate && f.status === 'pending' && (
                    <div className="flex items-center gap-1.5 shrink-0">
                      <Btn size="xs" variant="success" onClick={() => decide(f, 'approved')}><Icon name="check" className="w-3 h-3"/>Approve</Btn>
                      <Btn size="xs" onClick={() => decide(f, 'flagged')}>Flag</Btn>
                      <Btn size="xs" variant="danger" onClick={() => decide(f, 'rejected')}>Reject</Btn>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        )}
      </Card>
    </div>
  );
}

Object.assign(window, { CustomerFeedbackForm, CustomerFeedbackPage, FeedbackTokenGenerator, FEEDBACK_RATING_LABEL });
